EKF Test

In [2]:
# run this block to enable autoreload of modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from nonlinear_filtering_ekf import *
import numpy as np
import matplotlib.pyplot as plt

In [10]:
"""
    @param  K_f: camera intrinisic matrix (2, 2)
    @param  p:   point (3, 1)
    @param  c:   optical center (2, 1)
    @param  R:   rotation matrix of camera 2 wrt camera 1 (3, 3)
    @param  t:   translation vector of camera 2 wrt camera 1 (3, 1)
    @return z:   measurement (2, 1)
"""

K_f = np.array([[1, 1], [1, 1]])
p = np.array([[1, 1, 1]]).reshape((3,1))
c = np.array([[1, 1]]).reshape((2,1))
R = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
t = np.zeros((3,1))
# z = (K_f * p[2]) @ np.array([[p[0], p[1]]]).reshape((2,1)) + c
z1 = measurement_model_1(K_f, p, c)
z2 = measurement_model_2(K_f, p, c, R, t)

print("z1: ")
print(z1)
print()
print("z2: ")
print(z2)

z1: 
[[3.]
 [3.]]
z2: 
[[3.]
 [3.]]


In [18]:
"""
    @param  K_f: camera intrinisic matrix (2, 2)
    @param  p:   point (3, 1)
    @param  c:   optical center (2, 1)
    @param  R:   rotation matrix of camera 2 wrt camera 1 (3, 3)
    @param  t:   translation vector of camera 2 wrt camera 1 (3, 1)
    @return z:   measurement (2, 1)
"""

K_f = np.array([[1, 1], [1, 1]])
p = np.array([[1, 1, 1]]).reshape((3,1))
c = np.array([[1, 1]]).reshape((2,1))
R = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
t = np.zeros((3,1))

H1 = measurement_Jacobain_1(K_f, p)
H2 = measurement_Jacobain_2(K_f, p, R, t)

print("H1: ")
print(H1)
print()
print("H2: ")
print(H2)

H1: 
[[ 1.  1. -2.]
 [ 1.  1. -2.]]

H2: 
[[0. 0. 0.]
 [0. 0. 0.]]


Particle Filter Test

In [1]:
from nonlinear_filtering_pf import *

In [4]:
x = np.ones((3,))
w = np.ones((3,1))

x_pred = np.zeros((3,1)) # placeholder
x_pred = x.reshape((3,1)) + w

# x_pred = particle_filter(x, w)
print(x_pred.shape)

(3, 1)
